target-version = "py313"

[lint]
extend-select = [
    "I",  # import sorting
    "S", # bandit for security
    "B", # bugbear for likely bugs
    "T100", # Leftover breakpoints
    "PTH", # pathlib best practices
    "C90", # complexity
    "PD", # Pandas
    # "DOC", # docstring style
    # "D", # docstring style
    "F", # pyflakes
    "UP", # upgrade language features
    "FURB", # update python syntax patterns
]

[lint.per-file-ignores]
"**/tests/**.py" = ["S101"] # allow asserts in tests

[lint.isort]
known-first-party = ["common"]
