[tool.ruff]
extend = "../../ruff.toml"
lint.isort.known-local-folder = [ "hohonu_api" ]

[tool.pytest.ini_options]
pythonpath = "."

[tool.coverage.run]
omit = [
  ".pixi/*",
]

[tool.pixi.workspace]
authors = [ "Alex Kerney <abk@mac.com>" ]
channels = [ "conda-forge" ]
name = "s3_timeseries"
platforms = [ "linux-64", "linux-aarch64" ]
version = "0.1.0"

[tool.pixi.tasks]

[tool.pixi.dependencies]
ioos_qc = ">=2.2.1,<3"
pandas = ">=3.0.1,<4"
pydantic = ">=2.11.9,<3"
httpx = ">=0.28.1,<0.29"
xarray = ">=2025.9.0,<2026"
netcdf4 = ">=1.7.2,<2"
sentry-sdk = ">=2.43.0,<3"
dagster = ">=1.11.11,<2"
s3fs = ">=2025.9.0,<2026"
parse = ">=1.20.2,<2"
dagster-k8s = ">=1!0.27.11,<1!0.28"
dagster-postgres = ">=1!0.27.11,<1!0.28"
dagster-aws = ">=1!0.27.11,<1!0.28"
pint = ">=0.25,<0.26"
pyyaml = ">=6.0.2,<7"

[tool.pixi.feature.dev.dependencies]
pytest = "*"
pytest-recording = ">=0.13.4,<0.14"
pytest-cov = "*"

[tool.pixi.feature.dev.tasks]
pytest = "pytest -vv --ignore=common --record-mode=once"

[tool.pixi.environments]
dev = [ "dev" ]
