name: Core

on:
  push:
    branches: [main]
    tags: ["*"]
  pull_request:

concurrency:
  group: ${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build_backend:
    name: Build backend Python Docker image
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.11.1

    - name: Build Backend
      uses: docker/build-push-action@v6.18.0
      with:
        context: ./backend
        push: false
        tags: gmri/buoy_retriever_backend:latest

  build_frontend:
    name: Build Next.js frontend Docker image
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.11.1

    - name: Build Frontend
      uses: docker/build-push-action@v6.18.0
      with:
        context: ./frontend
        push: false
        tags: gmri/buoy_retriever_frontend:latest
        build-args: |
          NEXT_PUBLIC_BACKEND_URL=https://oso.ioos.us
          NEXT_PUBLIC_SENTRY_DSN=${{ secrets.NEXT_PUBLIC_SENTRY_DSN }}

  test_common:
    name: Test common package
    runs-on: ubuntu-24.04
    timeout-minutes: 10

    strategy:
      matrix:
        python-version:
          - "3.13"
          # - "3.14"

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Set up Python
      uses: astral-sh/setup-uv@v6
      with:
        working-directory: ./common
        python-version: ${{ matrix.python-version }}

    - name: Run tests
      working-directory: ./common
      run: |
        uv run pytest -vv --cov-report=xml --junitxml=junit.xml -o junit_family=legacy

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        flags: common

    - name: Upload test results to Codecov
      if: ${{ !cancelled() }}
      uses: codecov/test-results-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
